name: Electric Tractor Info
favicon: null
layout_spectrum: 0.00103
typography_spectrum: 0.81611
title: Electric Tractor Info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#646867'
    - '#fefefe'
    - '#23cc1e'
    - '#65fc36'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0
  rhythmicContrast: 1
purpose: []
