name: Electric Tractor Info
favicon: null
layout_spectrum: 0.2423
typography_spectrum: 0.81611
title: Electric Tractor Info
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060608'
    - '#b4dafe'
    - '#ab9e8e'
    - '#544a48'
    - '#fcd72d'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.8125
  rhythmicContrast: 0.75
purpose: []
