typography_spectrum: 0.81611
color:
  brandColors:
    - '#000000'
    - '#646867'
    - '#fefefe'
    - '#23cc1e'
    - '#65fc36'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00103
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: info@electrictractor.info
name: Electric Tractor Info
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Electric Tractor Info
purpose: []
